#!/bin/bash
gcc -o keygen keygen.c -std=gnu99 -Wall
gcc -o otp_enc otp_enc.c -std=gnu99 -Wall
gcc -o otp_enc_d otp_enc_d.c -std=gnu99 -Wall
gcc -o otp_dec otp_dec.c -std=gnu99 -Wall
gcc -o otp_dec_d otp_dec_d.c -std=gnu99 -Wall
